docs: update docs to show service principal login is now supported
hashicorp/terraform-provider-azuread pull request #1266
Opened 2023-12-01 16:35 UTC by jaredfholgate

This is a documentation only update to provide details on how to use az cli --service-principal and az cli --identity login since support was added in 2.35.0.

2023-12-05 14:38 UTC, manicminer requested changes
Hi @jaredfholgate, thanks for suggesting this change. Our language choice here was intentional; whilst authenticating az-cli with a service principal can and does work, we don't officially support this. Historically, az-cli authentication with a service principal did not work due to limitations of the tool, but with SDK advancements in the provider we have been able to permit this more recently. However, we do still recommend that practitioners use the native support for service principals, as it is more robust, more performant, and doesn't rely on a third party tool. So whilst we don't explicitly prevent authenticating az-cli in this way, we also can not strictly guarantee that this will always work as capabilities in the provider continue to progress.

I think we would be open to amending the docs to better represent this position, if you'd like to have a go at that? It would not need to include the technical context above, but could indicate the essential message that it might work but it's not supported in production and we recommend using the native authentication support.

2023-12-06 11:03 UTC, jaredfholgate commented
> Hi @jaredfholgate Jared Holgate FTE, thanks for suggesting this change. Our language choice here was intentional; whilst authenticating az-cli with a service principal can and does work, we don't officially support this. Historically, az-cli authentication with a service principal did not work due to limitations of the tool, but with SDK advancements in the provider we have been able to permit this more recently. However, we do still recommend that practitioners use the native support for service principals, as it is more robust, more performant, and doesn't rely on a third party tool. So whilst we don't explicitly prevent authenticating az-cli in this way, we also can not strictly guarantee that this will always work as capabilities in the provider continue to progress.
> 
> I think we would be open to amending the docs to better represent this position, if you'd like to have a go at that? It would not need to include the technical context above, but could indicate the essential message that it might work but it's not supported in production and we recommend using the native authentication support.

Hi @manicminer. Thanks for the feedback. Just to provide some insight into the reason for raising this change. When using Workload identity federation (OIDC) auth with Azure DevOps (and possibly GitHub and other tools), the id token is limited to 10 minutes. In some scenarios this can cause issues as even though Terraform exchanges the id token for an access token, it can try to do this more than once. The specific example being `terraform test`, where tests are executed sequentially and each test initialises the provider. If the tests last longer than 10 minutes, the run fails. However, if we use az-cli auth, this limitation is removed since the access token is cached by az-cli instead and the `azurerm`, `azuread` or `azapi` provider does not attempt to get a new access token.

I will look to update the wording as suggested, but could be worth a separate discussion. The Azure DevOps product group may be able to support the relevant testing required to make this a supported option on all three providers. It would also be great if the backend in terraform core supported this auth too (see here: https://github.com/hashicorp/terraform/issues/34322), although less important for the `terraform test` use case.

2023-12-14 19:22 UTC, manicminer commented
@jaredfholgate Thanks for the additional info. If we're failing due to short ID token validity/expiry, then I'd suggest that's something we should definitely look to improve.

In terms of updating our docs though, I would not want to specifically call out Azure DevOps as a scenario where users might want to use az-cli instead, without first trying to improve the native support.

2024-05-08 18:24 UTC, manicminer approved these changes
@jaredfholgate Thanks again for suggesting this documentation change. Due to the necessary use of az-cli in some environments, we now fully support authenticating as a service principal via az-cli. Due to this, I'd be happy to make these changes to the authentication guide. I've also expanded the examples a little using the same placeholder values that we use in other auth guides.

2024-05-08 18:24 UTC, manicminer commented on docs/guides/azure_cli.md
> +* Prior to version 2.35, authenticating via the Azure CLI was only supported when using a User Account. For example `az login --service-principal` was not supported and you had to use either a [Clien
```suggestion
* Prior to version 2.35, authenticating via the Azure CLI was only supported when using a User Account. For example `az login --service-principal` was not supported and it was necessary to use either a [Client Secret](service_principal_client_secret.html) or a [Client Certificate](service_principal_client_certificate.html). From 2.35 upwards, authenticating via the Azure CLI is supported when using a Service Principal or Managed Identity. However, we still recommend using native provider support for Service Principal or Managed Identity authentication wherever possible.
```

2024-05-08 18:24 UTC, manicminer commented on docs/guides/azure_cli.md
> +az login --service-principal -u "CLIENT_ID" -p "CLIENT_SECRET" --tenant "TENANT_ID" --allow-no-subscriptions
```suggestion
az login --service-principal \
         --username 00000000-0000-0000-0000-000000000000 \
         --password "MyCl1eNtSeCr3t" \
         --tenant 10000000-2000-3000-4000-500000000000 \
         --allow-no-subscriptions
```

2024-05-08 18:24 UTC, manicminer commented on docs/guides/azure_cli.md
> +az login --service-principal -u "CLIENT_ID" -p "CERTIFICATE_PEM" --tenant "TENANT_ID" --allow-no-subscriptions
```suggestion
az login --service-principal \
         --username 00000000-0000-0000-0000-000000000000 \
         --password /path/to/certificate \
         --tenant 10000000-2000-3000-4000-500000000000 \
         --allow-no-subscriptions
```

2024-05-08 18:24 UTC, manicminer commented on docs/guides/azure_cli.md
> +az login --service-principal -u "CLIENT_ID" --tenant "TENANT_ID" --allow-no-subscriptions
```suggestion
az login --service-principal \
         --username 00000000-0000-0000-0000-000000000000 \
         --tenant 10000000-2000-3000-4000-500000000000 \
         --allow-no-subscriptions
```

2024-05-08 18:24 UTC, manicminer commented on docs/guides/azure_cli.md
> +az login --identity --username "CLIENT_ID" --allow-no-subscriptions
```suggestion
az login --identity \
         --username 00000000-0000-0000-0000-000000000000 \
         --allow-no-subscriptions
```

2024-05-08 18:33 UTC, merged