azuread_user: support employee hire date
hashicorp/terraform-provider-azuread pull request #1437
Opened 2024-07-17 09:37 UTC by kang8

Closed: #1436

2024-09-12 10:06 UTC, kang8 commented
Hi @manicminer, Can you please take a look when you have a chance? 

The code has been tested on my end.

2024-10-04 12:29 UTC, Threpio commented
Code looks good from me too (if that matters)

Just curious as to whether the time that is passed to Microsoft has to include the Hour, Minute and Second part or if it can be just a date?

2024-10-08 10:41 UTC, kang8 commented
> Just curious as to whether the time that is passed to Microsoft has to include the Hour, Minute and Second part or if it can be just a date?

This is very interesting. 

From the perspective of the API, it can specify hours, minutes and seconds. 

<img width="1042" alt="image" src="https://github.com/user-attachments/assets/798ef813-4c5b-445f-a1e8-8ad4ea2f5331">


But on the UI, it can only be a date.

<img width="988" alt="image" src="https://github.com/user-attachments/assets/e51a275d-dd3d-4da0-a094-c2dd583bb590">

2024-10-23 09:55 UTC, kang8 commented
Switch this PR to draft for now. After rebasing to the latest master, I noticed significant changes in the code structure. I will mark it as ready once I've finished making the necessary adjustments.

2024-11-05 13:31 UTC, jackofallops requested changes
Thanks @kang8 - Just one minor change needed, then I think this will be good to go.

Thanks

2024-11-05 13:31 UTC, jackofallops commented on docs/resources/user.md
> +* `employee_hire_date` - The hire date of the user, formatted as an RFC3339 date string (e.g. `2018-01-01T01:02:03Z`).
```suggestion
* `employee_hire_date` - (Optional) The hire date of the user, formatted as an RFC3339 date string (e.g. `2018-01-01T01:02:03Z`).
```

2024-11-05 13:49 UTC, kang8 commented
@jackofallops thanks for your review, I applied the patch.

2024-11-08 02:41 UTC, kang8 commented
Hi @jackofallops, could you please take another look when you have a moment? Thank you!

2025-01-15 09:37 UTC, jackofallops approved these changes
Thanks @kang8 for the changes, and apologies for the long delay in looping back to this, it's been a very busy few months! 🙈 

This LGTM now and the tests are looking good:
![image](https://github.com/user-attachments/assets/eb36e632-4e9c-4cb2-94d5-ea968e40c3d1)

2025-01-15 09:41 UTC, merged