azuread_conditional_access_policy: support includeAuthenticationContextClassReferences and applicationFilter of conditions
hashicorp/terraform-provider-azuread pull request #1534
Opened 2024-10-17 09:54 UTC by kenchan0130

FIX: #882

2024-10-17 10:21 UTC, kenchan0130 commented on docs/resources/conditional_access_policy.md
> +* `included_authentication_context_class_references` - (Optional) A list of authentication context class reference to include. Supported values are `c1` through `c99`.
I see in [the API docs](https://learn.microsoft.com/ja-jp/graph/api/resources/conditionalaccessapplications?view=graph-rest-beta#properties) that it only supports IDs up to `c25`,
In fact, [the official doc](https://learn.microsoft.com/en-us/entra/identity/conditional-access/concept-conditional-access-cloud-apps#configure-authentication-contexts) states that IDs can be used up to `c99`.

2024-10-27 05:08 UTC, kenchan0130 commented
@katbyte @mbfrahry

Is it possible to be reviewed or get an advice about this please?

2024-11-04 07:35 UTC, jackofallops requested changes
Hi @kenchan0130 - before we do a full review, can you add acceptance test coverage for the new properties and validation conditions?

Thanks

2024-11-05 15:59 UTC, kenchan0130 commented
@jackofallops 

> Hi @kenchan0130 - before we do a full review, can you add acceptance test coverage for the new properties and validation conditions?
> 
> Thanks

This provider does not yet have a terraform resource to create an authentication context. So unfortunately I am unable to add a test on the attributes.
Should I create implementations (in another PR of course) of the authentication context resource?

2025-01-04 13:37 UTC, SuryenduB commented
Hi Team, can you please review this PR. We will need support for : included_authentication_context_class_references

2025-01-31 18:26 UTC, mjendza commented
hi, @kenchan0130 @jackofallops do you need any support to finish the PR and merge the feature?

2025-07-01 02:50 UTC, kenchan0130 commented
@jackofallops 

> Could you please give me your opinion on this?
> I intend to follow the policy of the maintainers.

Please let me know if you need more information concerning this matter.

2025-08-14 03:31 UTC, kenchan0130 commented
The `filter` is supported by https://github.com/hashicorp/terraform-provider-azuread/pull/1744.
I will change this PR only includeAuthenticationContextClassReferences scope.

2026-09-20 09:26 UTC, kenchan0130 commented
I'm closing this PR due to a lack of reviews, which suggests this provider might not be maintained or accepting new changes anymore.

To anyone coming here with the same issue, I'd suggest switching to:
https://registry.terraform.io/providers/deploymenttheory/microsoft365/latest/docs/resources/graph_beta_identity_and_access_conditional_access_policy

2026-09-20 09:26 UTC, closed without merging