principal_type_data_source - Feature - issue #824
hashicorp/terraform-provider-azuread pull request #847
Opened 2022-07-18 12:02 UTC by Threpio

2022-07-19 10:28 UTC, Threpio commented on internal/services/directoryobjects/principal_type_data_source.go
> +	directoryObject = *obj
@manicminer - I am pretty sure this is not the way to do it. This is the last thing other than the naming convention to be sorted for this PR/Fix to be good to go I think :)

2022-08-05 01:30 UTC, manicminer requested changes
Hi @Threpio, thanks for working on this PR. This is looking pretty good! I have made some suggestions inline below, and we will also need to add some acceptance tests for this data source.

If you can take a look at the comments below, and look to add one or two acceptance tests (take a look at some other data sources for inspiration :), then I'll be happy to take another look. Thanks!

2022-08-05 01:30 UTC, manicminer commented on docs/data-sources/principal_type.md
> +  value = "${data.azuread_principal_type.example.type}"
No need for interpolation here
```suggestion
  value = data.azuread_principal_type.example.type
```

2022-08-05 01:30 UTC, manicminer commented on internal/services/directoryobjects/principal_type_data_source.go
> +	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
Let's tidy up these imports
```suggestion
	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/hashicorp/terraform-provider-azuread/internal/clients"
	"github.com/hashicorp/terraform-provider-azuread/internal/tf"
	"github.com/hashicorp/terraform-provider-azuread/internal/validate"
	"github.com/manicminer/hamilton/msgraph"
	"github.com/manicminer/hamilton/odata"
```

2022-08-05 01:30 UTC, manicminer commented on docs/data-sources/principal_type.md
> +Gets the OData Object type for a single given Object ID.
```suggestion
Retrieves the OData type for a generic directory object having the provided object ID.
```

2022-08-05 01:30 UTC, manicminer commented on internal/services/directoryobjects/principal_type_data_source.go
> +
```suggestion
	var directoryObject msgraph.DirectoryObject

```

2022-08-05 01:30 UTC, manicminer commented on internal/services/directoryobjects/principal_type_data_source.go
> +	obj, _, err := client.Get(context.Background(), objectId, odata.Query{})
```suggestion
	directoryObject, _, err := client.Get(context.Background(), objectId, odata.Query{})
```

2022-08-05 01:30 UTC, manicminer commented on internal/services/directoryobjects/principal_type_data_source.go
> +		return nil
```suggestion
		return tf.ErrorDiagPathF(nil, "object_id", "Directory Object with ID %q was not found", objectId)
```

2022-08-05 01:30 UTC, manicminer commented on internal/services/directoryobjects/principal_type_data_source.go
> +	}
```suggestion
	}
	if directoryObject == nil {
		return tf.ErrorDiagF(fmt.Errorf("nil object returned for directory object with ID: %q", objectId), "Bad API Response")
	}
```

2022-08-05 01:30 UTC, manicminer commented on internal/services/directoryobjects/principal_type_data_source.go
> +	// There are many more types to switch here - These are the ones added per the issue
```suggestion
```

2022-08-06 17:46 UTC, Threpio commented
Most of the comments have been applied and committed -Sorry for the horrible commit mess.

I am not sure that I have handled the `directoryObject` object properly now that I have changed it to a pointer from the client.Get function.

I will work on the tests asap.

2022-08-08 07:31 UTC, manicminer commented
@Threpio Thanks, I'll take another look once the tests are pushed. Don't worry about the commit history, we can squash it :)

2022-08-08 10:59 UTC, Threpio commented
Tests have been added -I cannot apply the last suggestion as it is outdated and yet not updated.

For the tests I have done 3 success cases - I do not see examples of failing to terraform configuration being used for different unit tests and so have not written these. The docs are linted but the content might need a 5-minute review.

2022-08-25 15:19 UTC, manicminer approved these changes
Hi @Threpio, many thanks for working on this and for adding the tests - which should be enough to cover usage of this data source.

I've run through this again and made some changes, mainly renaming the data source from `azuread_principal_type` to `azuread_directory_object` - because I expect we'll support additional object types in future and this will help us avoid deprecating a data source in order to rename it.

In addition to that, I've made some fixes to the tests, added some nil checking that I missed on my first review, and made some documentation updates. I added the latter as inline suggestions below to give you an idea of how we like to structure and word the docs.

This is a great addition, many thanks for your effort on this! As I have made some additional changes, I'm going to open this for another maintainer to review but pending any other changes I'm happy for this to be merged and added to the provider.

2022-08-25 15:19 UTC, manicminer commented on docs/data-sources/directory_object.md
> +  object_id = "object-id"
We like to use syntactically appropriate but obviously-fake values in example configs :)
```suggestion
  object_id = "00000000-0000-0000-0000-000000000000"
```

2022-08-25 15:19 UTC, manicminer commented on docs/data-sources/directory_object.md
> +
We should include an Arguments section here

```suggestion

## Argument Reference

The following arguments are supported:

* `object_id` - (Optional) Specifies the Object ID of the directory object to look up.

```

2022-08-25 15:19 UTC, manicminer commented on docs/data-sources/directory_object.md
> +*`object_id` - The object_id specified.
```suggestion
*`object_id` - The object ID of the directory object.
```

2022-08-25 15:19 UTC, manicminer commented on docs/data-sources/directory_object.md
> +*`type` - The type of the object
```suggestion
*`type` - The shortened OData type of the directory object. Possible values include: `Group`, `User` or `ServicePrincipal`.
```

2022-08-25 15:19 UTC, manicminer commented on docs/data-sources/directory_object.md
> +When authenticated with a service principal, this data source requires either `Group.Read.All` or `Directory.Read.All`
```suggestion
When authenticated with a service principal, this data source requires either `User.Read.All`, `Group.Read.All` or `Directory.Read.All`, depending on the type of object being queried.
```

2022-08-25 18:27 UTC, katbyte approved these changes
LGTM 🦀

2022-08-25 21:52 UTC, merged