Add azuread_directory_role_eligibility_schedule_request resource
hashicorp/terraform-provider-azuread pull request #974
Opened 2023-01-12 09:04 UTC by JonasBak

This PR adds a `azuread_directory_role_eligibility_schedule_request` resource. We would like to be able to manage eligible roles in PIM with terraform. This PR lets us do it like this:

```
resource "azuread_directory_role_eligibility_schedule_request" "example" {
  role_definition_id = "00000000-0000-0000-0000-000000000000"
  principal_id       = "00000000-0000-0000-0000-000000000000"
  directory_scope_id = "/"
  justification      = "abc"
}
```

This is a pretty bare-bones version of the resource, but it gives us what we need for now. I have also opened a PR in https://github.com/manicminer/hamilton here: https://github.com/manicminer/hamilton/pull/204.

As I wrote in the other PR, I havn't written any tests, as I wanted to get some input first. The user/service principal requires [a role and a permission](https://learn.microsoft.com/en-us/graph/api/resources/privilegedidentitymanagementv3-overview?view=graph-rest-1.0#permissions-and-privileges) to be able to use the API, should I set these roles and permissions up as part of the tests?

2023-04-26 04:04 UTC, joraff commented
Anything I can do to help keep this moving? Will the work in hamilton need to be completed first?

2023-05-03 11:32 UTC, JonasBak commented
I rebased and added a basic test, I did the same for the PR in hamilton.

2023-07-14 01:21 UTC, manicminer requested changes
Hi @JonasBak, thanks for working on this!

This is off to a great start. I've made a suggestion inline below. It also looks like we're missing documentation for the new resource, if you can look at these then I'll be happy to take another look and we can see about merging this. Thanks!

2023-07-14 01:21 UTC, manicminer commented on internal/services/directoryroles/directory_role_eligibility_schedule_request_resource.go
> +	}
We have a helper func for this `helpers.WaitForUpdate()`

2023-07-18 12:44 UTC, StickNitro commented
Any update on this PR, I see the upstream changes are available with v0.62.0, this would be extremely beneficial to a piece of work I need to do

2023-07-31 08:23 UTC, JonasBak commented
I've rebased with main, added some docs, and added `helpers.WaitForUpdate()` as suggested

2023-09-20 10:31 UTC, JonasBak commented
@manicminer Could you take a look at this again?

2023-09-22 00:37 UTC, manicminer approved these changes
@JonasBak Thanks for the reminder and apologies for the delay in re-reviewing. I have only one minor suggestion regarding the import validation (see below) which I'll update. Other than that, this looks great and the test passes!

I had a go at adding support for `appScopeId` too, but I struggled to work out what to specify for this field as the API seems to silently ignore it instead of erroring (I tried an app ID, object ID of an application, object ID for a service principal). We can look to add this later.

2023-09-22 00:37 UTC, manicminer commented on internal/services/directoryroles/directory_role_eligibility_schedule_request_resource.go
> +			}
It looks like the ID is a UUID so we should validate this for imports

```suggestion
			if _, err := uuid.ParseUUID(id); err != nil {
				return fmt.Errorf("specified ID (%q) is not valid: %s", id, err)
			}
```

2023-09-22 00:49 UTC, manicminer commented
Test results

<img width="605" alt="Screenshot 2023-09-22 at 01 49 27" src="https://github.com/hashicorp/terraform-provider-azuread/assets/251987/3b6c4539-86f1-49e5-a47a-28d670b4e342">

2023-09-22 00:50 UTC, merged

2023-09-22 00:52 UTC, joraff commented
@manicminer Thank you for approving this! We've been wanting to use it for a while.

FWIW - I don't think `appScopeId` is fully implemented; possibly reserved for future use? The default value of `/` is all that works. `directoryScopeId` is what can scope to an admin unit.

2023-09-22 00:54 UTC, manicminer commented
No problem, sorry again for the delay. Thanks for the feedback; I was able to scope a request to an application using the Portal, but alas the portal uses the PIM data plane API - so perhaps the MS Graph interface is incomplete as you say.

2023-09-22 01:02 UTC, joraff commented
Oh! Perhaps it is used now. It's been a while since I've done an assignment via the portal. Thanks to this, it might be a bit longer ;)